### ISSUE TITLE
guard-nanoc not compatible with nanoc 4

### ISSUE THREAD

**Issue by ddfreyne** [guard/guard-nanoc#20]
guard-nanoc does not work with nanoc 4.

See [this tweet](https://twitter.com/cdlm/status/603653876064071680).

**Comment by cdlm** [comment]
For reference, here are my `Guardfile`:
```ruby
guard 'nanoc' do
  watch('nanoc.yaml')
  watch('rules.rb')
  watch(%r{^(content|layouts|lib)/.*$})
end
```
…and the error dump:
```
$ bundle exec guard
00:42:37 - ERROR - Could not load 'guard/nanoc' or find class Guard::Nanoc
00:42:37 - ERROR - Error is: cannot load such file -- guard/guard
00:42:37 - ERROR - /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-nanoc-1.0.2/lib/guard/nanoc.rb:4:in `require'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-nanoc-1.0.2/lib/guard/nanoc.rb:4:in `<top (required)>'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/plugin_util.rb:105:in `require'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/plugin_util.rb:105:in `rescue in plugin_class'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/plugin_util.rb:97:in `plugin_class'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/plugin_util.rb:56:in `initialize_plugin'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/internals/plugins.rb:26:in `add'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/dsl.rb:185:in `block in guard'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/dsl.rb:182:in `each'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/dsl.rb:182:in `guard'
> [#] /Users/damien/Documents/Website/nanoc/Guardfile:1:in `evaluate'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `instance_eval'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `evaluate'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/guardfile/evaluator.rb:91:in `evaluate'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard.rb:134:in `_evaluate'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard.rb:49:in `setup'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/commander.rb:32:in `start'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/cli.rb:113:in `start'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:32:in `execute'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#] /Users/damien/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/guard-2.12.5/bin/_guard-core:11:in `<main>'
00:42:37 - ERROR - Invalid Guardfile, original error is:
> [#]
> [#] Could not load class: "Nanoc",
> [#] backtrace:
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/plugin_util.rb:57:in `initialize_plugin'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/internals/plugins.rb:26:in `add'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:185:in `block in guard'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:182:in `each'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:182:in `guard'
> [#] 	(dsl)> ./Guardfile:1:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `instance_eval'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/dsl.rb:377:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/guardfile/evaluator.rb:91:in `evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard.rb:134:in `_evaluate'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard.rb:49:in `setup'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/commander.rb:32:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/cli/environments/valid.rb:16:in `start_guard'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/cli.rb:113:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
> [#] 	(dsl)> $GEM_PATH[0]/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:32:in `execute'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/lib/guard/aruba_adapter.rb:19:in `execute!'
> [#] 	(dsl)> $GEM_PATH[0]/gems/guard-2.12.5/bin/_guard-core:11:in `<main>'
```

**Comment by ddfreyne** [comment]
See #21.
